# Site settings
title: Rabindra Lamsal
general_email: r.lamsal@unimelb.edu.au
academic_email:

description: > # this means to ignore newlines until "baseurl:"
  I believe that the hunger to learn should never saturate.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://rlamsal.com.np" # the base hostname & protocol for your site

#twitter_username: rabindra_lamsal
github_username: 
#linkedin_username: rabindralamsal
facebook_username: 
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
